spring:
  application:
    name: address-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/micro
    username: kyawzayar
    password: kyawzayar
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: 8081
  servlet:
    context-path: /address-app/api
eureka:
  client:
    # the url of discovery service in case of different ip and port
    # default = http://localhost:8761/eureka
    service-url:
      defaultZone: http://localhost:5000/eureka
  instance:
    # this is the heartbeat interval
    # call eureka server api every 30s, 30s is default
    lease-renewal-interval-in-seconds: 10
    # Eureka server didn't get any heartbeat from this in 90s it will remove, 90s is default
    lease-expiration-duration-in-seconds: 30
    # we can give any data we want to pass to Map<String, String>
    metadata-map:
      context-path: /address-app/api
      from: myanmar

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
info:
  app:
    name: Address Application
    version: 1.0